### ISSUE TITLE
Why static class instead of namespace'd functions?

### ISSUE THREAD

**Issue by shadowhand** [php-fp/php-fp-combinators#1]
As the title says, why a static class instead of a set of functions in a namespace?

**Comment by i-am-tom** [comment]
The reason was that, as far as I'm aware, you can't export a "decorated" function. As all these functions would ideally be wrapped with the `curry` function, this was the last-ditch attempt :/ If you have a better fix, I'm 110% open to it!

**Comment by shadowhand** [comment]
What do you mean by "export"? This works fine:

```php
use function PhpFp\Combinator\compose;

$strictUcFirst = compose('ucfirst', 'strtolower');
```

**Comment by i-am-tom** [comment]
But this would also have to work:

```php
use function PhpFp\Combinator\compose;

compose('ucfirst', 'strtolower', 'bagels')
=== compose('ucfirst', 'strtolower')('bagels')
=== compose('ucfirst')('strtolower', 'bagels')
=== compose('ucfirst')('strtolower')('bagels')
=== 'BAGELS'
```

**Comment by i-am-tom** [comment]
You're definitely right - currying could just be done in each case within the function, and that might actually be a neater way to do it. Hmmm...

**Comment by shadowhand** [comment]
I wrote [highlander](https://github.com/shadowhand/highlander/blob/master/src/functions.php) for fun last night. Some of these functions are probably totally broken from a FP standpoint, and some of them definitely have bad algebra definitions. I'd love to contribute them to PhpFp if you think it would be a good starting point for "rebooting" combinators.

**Comment by i-am-tom** [comment]
Oo! Certainly some strange choices of names, but otherwise cool! I would still prefer these to be totally flexible in terms of argument supply, though... Maybe a case of writing:

```php
$secretlyCurriedX = curry(function () { ... })

function X(... $args) use ($secretlyCurriedX) {
    return $secretlyCurriedX(... $args);
}
```

If it turns out to be that simple, though, we can absolutely get them all in :D

**Comment by shadowhand** [comment]
Some of them are named because of limitations in PHP, like `consistent` instead of `constant` because the latter is native function. Certainly open to suggestions on better names though!

I'll work out a PR to make combinators into functions and then build off that.

**Comment by i-am-tom** [comment]
Yeah, nw :) As an initial glance:

| Name | Comment |
| ---:|:--- |
| `consistent` | `const` |
| `curry` | This function doesn't curry |
| `late` | Not sure what this does |
| `part` | ^ |
| `partial` | ^ |
| `possibly` | [`ifElse`](http://ramdajs.com/docs/#ifElse) |
| `call` | Is this the same as `late`? |
| `sequence` | Also not sure |
| `store` | ^ |

I think most of my confusion is coming from the type annotations; [I've written a little](http://www.tomharding.me/2017/03/08/fantas-eel-and-specification-2/) on the subject, which may help. Long and short: variadic functions are generally impossible with strict typing :(

**Comment by shadowhand** [comment]
`const` is a reserved word for classes. :(

**Comment by i-am-tom** [comment]
Haha, oh yeah! Sorry, haven't PHP'd in a long while :( In some functional settings, it gets called `K` (because it's the "K combinator"), but I guess that's not too intuitive...

**Comment by shadowhand** [comment]
- `const` is a reserved word for classes and `constant` is a native function :(
- `curry` is definitely badly named... it is really `partial` but I already had one implementation.
- `part`/`partial` was that bad attempt.
- `possibly` seems like a more elegant name for `ifElse`. Opinions. :)
- `call` is a funky one... it takes a method name and returns a `callable` that invokes the given method when passed an object. [test case](https://github.com/shadowhand/highlander/blob/master/tests/CallTest.php)
- `sequence` is a callable created from any number of callables, where each callable is executed in order and the output of the last is passed to the next. There's probably a name for this in FP, not sure what it is. Maybe it's just `compose` inverted? [test case](https://github.com/shadowhand/highlander/blob/master/tests/SequenceTest.php)
- `store` is like constant, except that the first time you invoke, it stores the passed value and then returns the same value every time after that. [test case](https://github.com/shadowhand/highlander/blob/master/tests/StoreTest.php)
